server:
  port: 8030

spring:
  application:
    name: customer-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


   
